# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_anybad_loc <- function(lower, upper) {
    .Call(`_tinycodet_rcpp_anybad_loc`, lower, upper)
}

#' @keywords internal
#' @noRd
.rcpp_convert_i0 <- function(n_matches, i) {
    .Call(`_tinycodet_rcpp_convert_i0`, n_matches, i)
}

#' @keywords internal
#' @noRd
.rcpp_convert_i1 <- function(n_matches, i) {
    .Call(`_tinycodet_rcpp_convert_i1`, n_matches, i)
}

#' @keywords internal
#' @noRd
.rcpp_alloc_stri_locate_ith <- function(p1, i) {
    .Call(`_tinycodet_rcpp_alloc_stri_locate_ith`, p1, i)
}

