# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_prep_ns <- function(ns, nms, pkg) {
    .Call(`_tinycodet_rcpp_prep_ns`, ns, nms, pkg)
}

