# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_anybad_loc <- function(lower, upper) {
    .Call(`_tinycodet_rcpp_anybad_loc`, lower, upper)
}

#' @keywords internal
#' @noRd
.rcpp_prep_ns <- function(ns, nms, pkg) {
    .Call(`_tinycodet_rcpp_prep_ns`, ns, nms, pkg)
}

#' @keywords internal
#' @noRd
.rcpp_Tmethods <- function(ns, nms, pkgs) {
    .Call(`_tinycodet_rcpp_Tmethods`, ns, nms, pkgs)
}

#' @keywords internal
#' @noRd
.rcpp_n_matches <- function(lst) {
    .Call(`_tinycodet_rcpp_n_matches`, lst)
}

#' @keywords internal
#' @noRd
.rcpp_convert_i0 <- function(n_matches, i) {
    .Call(`_tinycodet_rcpp_convert_i0`, n_matches, i)
}

#' @keywords internal
#' @noRd
.rcpp_convert_i1 <- function(n_matches, i) {
    .Call(`_tinycodet_rcpp_convert_i1`, n_matches, i)
}

#' @keywords internal
#' @noRd
.rcpp_alloc_stri_locate_ith <- function(p1, n_matches, i) {
    .Call(`_tinycodet_rcpp_alloc_stri_locate_ith`, p1, n_matches, i)
}

